# 26 July 2023


In [ ]:
print(1 + 3 * 2 - 5 + 4)
print(1 + 3 * (2 - 5) + 4)
print(5**2**2 * 3 + 1)
print(5 ** (2**2) * 3 + 1)
print(1 + 3 / 2)

In [ ]:
import math

print(math.pow(10, 5))
print(math.sqrt(10))

a = 1
b = -7
c = 10
x1 = ((-1 * b) - (math.sqrt(math.pow(b, 2) - (4 * a * c)))) / (2 * a)
x2 = ((-1 * b) + (math.sqrt(math.pow(b, 2) - (4 * a * c)))) / (2 * a)
print("Roots are", x1, x2)

print(math.log2(2 + math.sqrt(5)))

radius = 5.5
print(
    "The area of a circle with a radius of", radius, "is", math.pi * math.pow(radius, 2)
)

print(math.sin(2.5))

import cmath

a = 1
b = -2
c = 10
ix1 = ((-1 * b) - (cmath.sqrt(math.pow(b, 2) - (4 * a * c)))) / (2 * a)
ix2 = ((-1 * b) - (cmath.sqrt(math.pow(b, 2) - (4 * a * c)))) / (2 * a)
print("Roots are", ix1, ix2)

print("4! is", math.factorial(4))

from functools import reduce

print("Summation is", reduce(lambda p, q: p + q, [k for k in range(32, 128 + 1)]))
print("Product is", reduce(lambda p, q: p * q, [k for k in range(3, 17)]))

**Celsius to Fahrenheit**


In [ ]:
input_temperature = float(input("Temperatue in °C = "))
temperature_in_degree_farenheit = input_temperature * (9 / 5) + 32

print(input_temperature, "°C is", temperature_in_degree_farenheit, "°F")

**Fahrenheit ot Celsius**


In [ ]:
input_temperature = float(input("Temperatue in °F = "))

temperature_in_degree_celsius = (input_temperature - 32) * (5 / 9)

print(input_temperature, "°F is", temperature_in_degree_celsius, "°C")

**Meter to Foot**


In [ ]:
input_length = float(input("Length in Meter = "))
length_in_foot = input_length * 3.281
print(input_length, "Meter(s) is", length_in_foot, "Foot")

**Foot to Meter**


In [ ]:
input_length = float(input("Length in Foot = "))
length_in_meter = input_length / 3.281
print(input_length, "Foot is", length_in_meter, "Meter")

**Acre to Square Meter**


In [ ]:
input_area = float(input("Area in Acre = "))
area_in_square_meter = input_area * 4047
print(input_length, "Acre(s) is", area_in_square_meter, "Square Meter(s)")

**Square Meter to Acre**


In [ ]:
input_area = float(input("Area in Square Meter = "))
area_in_acre = input_area / 4047
print(input_length, "Square Meter(s) is", area_in_acre, "Acre(s)")

**Pound to Kilogram**


In [ ]:
input_mass = float(input("Mass in Pound = "))
mass_in_kilogram = input_mass / 2.205
print(input_mass, "Pound(s) is", mass_in_kilogram, "Kilogram(s)")

**Kilogram to Pound**


In [ ]:
input_mass = float(input("Mass in Kilogram = "))
mass_in_pound = input_mass * 2.205
print(input_mass, "Kilogram(s) is", mass_in_pound, "Pound(s)")

**John's Simple Interest**


In [ ]:
principal = 3000
time_in_year = 3
simple_interest = 3335.8

interest_rate = (simple_interest * 100) / (principal * time_in_year)

print("John is getting an annual interest rate of", interest_rate)

**`Heron's` Formula**


In [ ]:
a = 3
b = 4
c = 6

semi_perimeter = (a + b + c) / 2
area_of_triangle = math.sqrt(
    semi_perimeter * (semi_perimeter - a) * (semi_perimeter - b) * (semi_perimeter - c)
)
print(
    "Area of a Triangle with sides (in Meter)",
    a,
    ",",
    b,
    ", and",
    c,
    "is",
    area_of_triangle,
    "Square Meter(s)",
)

**Random Number Guess**


In [ ]:
import random

guess_start = 1
guess_stop = 100

computed_guess = random.randint(guess_start, guess_stop)

while True:
    guess = int(input("Guess it? "))
    if guess > computed_guess:
        print("Your guess is greater")
    elif guess < computed_guess:
        print("Your guess is smaller")
    else:
        print("Your guess is equal")
        break

# 27 July 2023


## Tuples

> Mutability 👎


In [3]:
books = (
    "ANSI C",
    "Java: The complete reference",
    "Discrete Mathematics and Applications",
)
authors = ("Brian Kernighan and Dennis Ritchie", "Herbert Schildt", "Kenneth H. Rosen")
language = ("English",)

print(books[-1:-3:-1])
print(books[-3:-1:1])
print(books[-3:-1:-1])

('Discrete Mathematics and Applications', 'Java: The complete reference')
('ANSI C', 'Java: The complete reference')
()


`in` operator with a Tuple


In [ ]:
print("ANSI C" in books)
books.index("ANSI C")

`id()` method


In [ ]:
id(books)

`del` operator


In [4]:
id(language)
del language
id(language)

NameError: name 'language' is not defined

**Operators for a Tuple**
| Operators | Description |
| --------- | --------------- |
| `+` | `Concatenation` |
| `*` | `Repetition` |


In [5]:
print(books + authors)
print(language * 3)

('ANSI C', 'Java: The complete reference', 'Discrete Mathematics and Applications', 'Brian Kernighan and Dennis Ritchie', 'Herbert Schildt', 'Kenneth H. Rosen')


NameError: name 'language' is not defined

`for` loop


In [ ]:
sum = 0
for x in tuple(range(10)):
    sum += x
print("Sum of first 10 whole numbers is", sum)

`range()` method

> Creates a sequence


In [ ]:
print(tuple(range(2, 100, 2)))

**Tuple Unpacking**


In [ ]:
print(*books)

## List

> Mutability 👍


In [ ]:
alphabets = [chr(i) for i in range(ord("a"), ord("z"))]
print(alphabets)

Indexing and Slicing


In [ ]:
print(alphabets[20])
print(alphabets[0:6])
print(alphabets[0:5:-1])

`for` loop


In [ ]:
for alphabet in alphabets:
    print(alphabet, end="")

`extend()` method

> Extends the list in-place with another `iterable`

> Returns `None`


In [ ]:
alphabets.extend("áàäéè")
print(alphabets)

# 28 July 2023


The `def` keyword


In [ ]:
def greet(message):
    print(message)
    return message


returned_message = greet("hello world")
print(returned_message)

The `*args` and `**kwargs` keywords


In [ ]:
def function(*args, **kwargs):
    print("args is", type(args))
    print("kwargs is", type(kwargs))


function()

In [ ]:
def sum(*args):
    if args:
        sum = 0
        for arg in args:
            sum += arg
        return sum
    else:
        return None


sum(*[x for x in range(10)])

# 31 July 2023


`lambda` function

> `lambda comma_seprated_arguments: expression`

> The `expression` is returned automatically to the caller


In [ ]:
f = lambda x, y=0: x**y

print(f(2, 3))
print(f(3))

In [ ]:
g = lambda x=0, y=0: x**3 + y**2 + 5

print(g())
print(g(1, 2))

**List comprehension**


In [ ]:
domain_name = "Library Mangement System"

paragraph_on_domain = f"A {domain_name} is a software that helps take the load \
off librarians and other library users. It does so by enabling them to \
digitally manage, organize and access the resources of a library like books, \
e-books, articles, journals, research papers, and such. It couples these along \
with OPAC, an Online Public Access Catalog allowing users to search for the \
resources in an efficient manner like filtering, sorting, etc.\nAll of these \
and more elevate the efficiency and thereby the productivity of the librarians \
whilst simultaneously improving the user experince by bringing all of these on \
their palm."

[print(x, end=", ") for x in domain_name]

In [ ]:
letters_in_domain_name = [letter for letter in domain_name]
print(letters_in_domain_name)

In [ ]:
vowels = ["a", "e", "i", "o", "u"]
vowels_in_domain_name = [letter for letter in domain_name if letter in vowels]

print(vowels_in_domain_name)

In [ ]:
uppercase_letters_in_domain_name = [
    letter for letter in domain_name if letter.isupper()
]
print(uppercase_letters_in_domain_name)

In [ ]:
uppercase_domain_name = [
    letter if letter.isupper() else letter.lower() for letter in domain_name
]
print("".join(uppercase_domain_name))

# 1 August 2023


## `Dictionary`

> Mutability 👍


In [ ]:
university = {
    "name": "CHRIST UNIVERSITY",
    "campus": "Bangalore Central",
    "deaneries": ["school of science", "school of arts"],
}

print(type(university))
print(university)

In [ ]:
print(university["name"])
print(university["campus"])

`get()` method


In [ ]:
print(university.get("name"))
print(university.get("names"))

`keys()` method


In [ ]:
university.keys()

`id()`

> `id()` gives the unique identification assigned to an object when it is created


In [ ]:
print(id(university))

`update()` method


In [ ]:
university.update({"campus": "Delhi NCR"})
print(university)

university["campus"] = "Bangalore Central"
print(university)

`values()` method


In [ ]:
print(university.values())

`pop()` method


In [ ]:
university.pop("deaneries")
print(university)

`del`


In [ ]:
del university["campus"]
print(university)

del university
id(university)

`for` loop


In [ ]:
for x in university:
    print(x)

for x in university.values():
    print(x)

`items()` method


In [ ]:
for k, v in university.items():
    print(k, v)

`copy()` method


In [ ]:
copy_of_university = university.copy()
print(copy_of_university)

print(id(copy_of_university) == id(university))

In [ ]:
def unpack(name, campus, deaneries):
    print(name, campus, sep=":")


unpack(**university)

# 3 August 2023


## `Set`

> Mutability 👍


In [ ]:
books = set(books)

print(books)

`len()`


In [ ]:
print(len(books))

`add()` method


In [ ]:
books.add("Headstart with Python")
print("Updated books are", books, sep="\n")

`update()` method


In [ ]:
books.update(["Database System Concepts", "Linux for System Administration"])
print(books)

`remove(), discard(), pop()` method

| Method      | Behaviour                                                                      |
| ----------- | ------------------------------------------------------------------------------ |
| `remove()`  | Throws `KeyError` if element is not found                                      |
| `discard()` | Same as `remove()` but **fails silently**                                      |
| `pop()`     | Remove and return element `1` in the set<br>Throws `KeyError` for an empty set |


In [ ]:
books.remove("Headstart with Python")
print(books)

books.discard("Headstart with Python")
print(books)

print("Popped", books.pop())

[`all()`](https://docs.python.org/3/library/functions.html?highlight=all#all)
[`any()`](https://docs.python.org/3/library/functions.html?highlight=any#any)


In [ ]:
i = [True, False]
print(all(i))
print(any(i))

## `frozenset()`

> Mutability 👎


In [ ]:
prices = frozenset([350, 1200, 849])
copies = frozenset([150, 75, 350, 500])

`union()` method


In [ ]:
u = prices.union(copies)
print(u)

`interesection()` method


In [ ]:
i = prices.intersection(copies)
print(i)

`difference()` method


In [ ]:
prices_d_copies = prices.difference(copies)
print(prices_d_copies)

copies_d_prices = copies.difference(prices)
print(copies_d_prices)

`symmetric_difference()` method


In [ ]:
prices.symmetric_difference(copies) == copies.symmetric_difference(prices)

# 4 August 2023


In [ ]:
t = (1, 2, 3)
l = list(t)
s = set(t)
d = {"t": t, "l": l, "s": s}

## Number System

> `Python3` follows the **Decimal Number System** by deafult


### Binary

> Binary number constants are prefixed with `0b`


In [ ]:
binary_of_2 = 0b10
print(binary_of_2)

`bin()` function


In [ ]:
bin(2)

In [ ]:
a = 0b011
b = 0b100

print(f"{a=}, {b=}")

### Octal

> Octal number constants are prefixed with `0o`


`oct()` function


In [ ]:
oct(3)

### Hexadecimal

> Hexadecimal number constants are prefixed with `0x`


`hex()` function


In [ ]:
hex(11)

## Module

> A `.py` file is a `module` in **Python3**


In [ ]:
import scratch

print("Hey there! I'll help you find S.I")
print("Give me a couple of info first!")

pa = float(input("Principal Amount? "))
y = int(input("Time in Years? "))
r = float(input("Interest Rate? "))
si = scratch.simple_intereset(principal=pa, years=y, rate=r)

print(
    f"Simple Interest comes out to be {si:.2f}",
)

# 8 August 2023


## Object Oriented Programming


### `Class`


In [ ]:
class Book:
    pass


book1 = Book()
book1.name = "Java The Complete Reference"
book1.price = 1200
print(f"{book1.__dict__ = }")

book2 = Book()
book2.title = "The C Programming Language"
book2.author = "Brian W. Kernighan"
print(f"{book2.__dict__ = }")

### `del`


In [ ]:
book1.copies = 75
print(f"{book1.copies = }")

del book1.copies
print(f"{book1.copies = }")

### Methods and Constructors


In [ ]:
class Book:
    def getTitle(self):
        return self.title

    def setTitle(self, title):
        self.title = title

    def copies(self, n):
        self.copies += n


some_book = Book()

some_book.setTitle("Discrete Mathematics and Its Applications")
print(some_book.getTitle())

Book.setTitle(some_book, "Data Structures and Algorithms")
print(some_book.getTitle())

### `__init__()`


In [ ]:
class Book:
    """This a Book class"""

    __currency = "\u20B9"
    __count = 0

    def __init__(self, title: str, author: [str], price: float) -> None:
        self.title = title
        self.author = author
        self.price = price
        self.copy = 1
        Book.__count += 1
        self.__index = Book.__count

    def setcopy(self, copy: int):
        self.copy = copy

    def _format_author(self):
        print()
        return ", ".join(self.author)

    def __str__(self) -> str:
        return f"---BOOK #{self.__index}---\n{self.title}\n~ {self._format_author()}\n{Book.__currency} {self.price}\n"

### `__doc__`


In [ ]:
print(Book.__doc__)

### `__str___`


In [ ]:
book1 = Book("Head First Python", ["Paul Barry", "Rohit Tank"], 1_147.0)
book2 = Book(
    "Python Crash Course: A Hands-On, Project-Based Introduction To Programming",
    ["Eric Mattnes"],
    2347.0,
)
print(book1, book2)

# 14 August 2023


## Inheritance

1. Single
2. Multilevel
3. Multiple
4. Hierarchichal
5. Hybrid


## Single Inheritance

In [ ]:
class School:
    def __init__(self, school):
        self.school = school

    def __str__(self):
        return f"School of {self.school}"


class Department(School):
    def __init__(self, school, department):
        super().__init__(school)
        self.department = department

    def __str__(self):
        return f"Department of {self.department}, {super().__str__()}"


a_school = School("Sciences")
a_department = Department(a_school.school, "Chemistry")
print(a_school)
print(a_department)

## Multiple Inheritance

In [ ]:
class Mom:
    def __init__(self, name) -> None:
        self.mom_name = name


class Dad:
    def __init__(self, name) -> None:
        self.dad_name = name


class Me(Mom, Dad):
    def __init__(self, name, mother_name, father_name) -> None:
        # super().__init__()
        Mom.__init__(self, mother_name)
        Dad.__init__(self, father_name)
        self.name = name

    def __str__(self):
        return f"{self.name} is a child of {self.mom_name} and {self.dad_name}"


print(Me("Bivas", "Pratima", "Ramesh"))

## Multilevel Inheritance

In [ ]:
class Switch:
    def __init__(self, on: bool = False):
        self.on = on

    def turn_on(self):
        self.on = True if not self.on else False

    def __str__(self):
        return f"Switch is {self.on}"


class Light(Switch):
    def __init__(self):
        super().__init__()

    def __str__(self):
        if self.on:
            return "Light is on"
        else:
            return "Light is off"


class Fan(Switch):
    def __init__(self):
        super().__init__()
        pass

    def __str__(self):
        if self.on:
            return "Fan is running"
        else:
            return "Fan is not runnning"


switch = Switch(True)
light = Light()
print(light)
light.turn_on()
print(light)

fan = Fan()
print(fan)
fan.turn_on()
print(fan)

# 17 August 2023

## Hierarchical Inheritance

In [ ]:
class School:
    def __init__(self) -> None:
        pass

    def __str__(self, name: str = None) -> str:
        if name is None:
            return "Base class 'School'"
        else:
            return f"School of {name}"


class SchoolOfScience(School):
    def __init__(self) -> None:
        self.school_name = "Science"

    def __str__(self) -> str:
        return super().__str__(self.school_name)


class SchoolOfPerformingArts(School):
    def __init__(self) -> None:
        self.school_name = "Performing Arts"

    def __str__(self) -> str:
        return super().__str__(self.school_name)


some_school = School()
print(SchoolOfScience())
print(SchoolOfPerformingArts())

## Hybrid Inheritance

In [ ]:
class SchoolOfComputerScience(SchoolOfScience, School):
    def __init__(self) -> None:
        super().__init__()

## Abstract Class

In [ ]:
from abc import ABC


class Shape(ABC):
    pass

## Exception Handling

```python
try:
    ...
except Exception:
    ...
```

In [ ]:
def divide(p, q):
    r = None
    try:
        r = p // q
    except ZeroDivisionError as e:
        print(e)
    except TypeError as e:
        print(e)
    else:
        print(r)


divide(5, 2)
divide("👎", "👍")

In [ ]:
cgpa = [9, 7, 6, 5, 10, 3, 9, 6, 6, 4]

print("Frequency of CGPA 6 is", cgpa.count(6))

cgpa.pop()
cgpa.append(3)
print("Last CGPA is", cgpa[-1])

print("Highest CGPA is", max(cgpa))

print("CGPA from lowest to highest is", sorted(cgpa))

avg = lambda iterable: sum(iterable) / len(iterable)
print("Average CGPA is", avg(cgpa))

In [ ]:
from random import choices

options = ("Y", "N")

responses = choices(options, k=10)
print("Response sheet:", responses)

numYes = responses.count(options[0])
numNo = responses.count(options[1])
print("Frequency of", options[0], "is", numYes)
print("Frequency of", options[1], "is", numNo)

percentYes = (numYes / len(responses)) * 100
print("Yes % is", percentYes)

print("Sorted Response Sheet is", sorted(responses))

f = responses.index(options[0])
print(options[0], "first occurs at index", f)

# 21 August 2023

In [ ]:
from collections import defaultdict


def stop(text: str) -> bool:
    """Stop infinite while loop"""
    return text.casefold() == "I am gonna call it night".casefold()


def sold(status: str) -> bool:
    """Check if stock was sold"""
    return status.casefold() == "s".casefold()


def bought(status: str) -> bool:
    """Check if stock was bought"""
    return status.casefold() == "b".casefold()


def buy(price: float, quantity: int, broker: defaultdict):
    """Buy `quantity` of qunatity stock each of price `price`"""
    broker.update({"Bought_Quantity": broker["Bought_Quantity"] + quantity})
    broker.update({"Bought": broker["Bought"] + price * quantity})


def sell(price: float, quantity: int, broker: defaultdict):
    """Sell `quantity` of qunatity stock each of price `price`"""
    broker.update({"Sold_Quantity": broker["Sold_Quantity"] + quantity})
    broker.update({"Sold": broker["Sold"] + price * quantity})


def broker():
    broker_output = defaultdict(int)

    while True:
        broker_input = input("Company, Quantity, Price, Status? ")

        if stop(broker_input):
            break

        try:
            _, quantity, price, status = broker_input.split(", ")
            quantity = int(quantity.strip())
            price = float(price.strip())
            status = status.strip().casefold()
        except ValueError:
            broker_input = input("Company, Quantity, Price, Status? ")
        else:
            if bought(status):
                buy(price, quantity, broker_output)
            elif sold(status):
                sell(price, quantity, broker_output)
            else:
                pass
    return broker_output


print(broker())

# 24 August 2023

In [3]:
ALPHABETS = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")


def ispangram(text: str = "") -> bool:
    """
    Check if a given text is a pangram or not

    A pangram is a sentence in which every letter of the alphabet is used atleast once
    """
    return len(set(text).intersection(ALPHABETS)) == len(ALPHABETS) / 2


def isheterogram(text: str = "") -> bool:
    """
    Check if a given text is a heterogram or not

    A heterogram is a word, phrase or a sentence in which no letter of the alphabet occurs more than once
    """
    return len(set(text).intersection(ALPHABETS)) == len(
        tuple(filter(lambda x: x.isalpha(), text))
    )


assert ispangram("the quick brown fox jumps over the lazy dog") == True
assert ispangram("geeks for geeks") == False
assert ispangram("the big dwarf only jumps") == False
assert ispangram("geeksforgeeks") == False

assert isheterogram("the quick brown fox jumps over lazy dog") == True
assert isheterogram("the big dwarf only jump s") == True
assert isheterogram("geeksforgeeks") == False

AssertionError: 

## Regular Expression

Method |
---|
`re.search()`|
`re.match()`|
`re.fullmatch()`|
`re.split()`|
`re.findall()`|

In [1]:
import re
import sys

text = " ".join(sys.argv)
print(text)
re.Match()

/home/bivas/devel/projects/python/.venv/lib/python3.10/site-packages/ipykernel_launcher.py --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"5ccdb368-db0c-42d0-9ffd-af7e2b665f58" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/bivas/.local/share/jupyter/runtime/kernel-v2-30173EJuFjwrRrFe.json


# 29 August 2023

## The `numpy` python package

In [2]:
import numpy

nparray = numpy.array([1, 2, 3, 4, 5])

print(nparray)
print(nparray[-1])
print(nparray[[0, 1, 3]])
print(nparray[9])

[1 2 3 4 5]
5
[1 2 4]


IndexError: index 9 is out of bounds for axis 0 with size 5

In [28]:
a_random = numpy.random.RandomState(seed=52)
x = a_random.randint(3, size=10)
print(x)

[1 0 1 2 0 0 1 2 2 1]


In [10]:
another_np_array = numpy.array([[1, 2, 3], [4, 5, 6]])
print(numpy.add.reduce(another_np_array))

[5 7 9]


In [5]:
print("Dimension =", nparray.ndim)
print("Size =", nparray.size)
print("Shape =", nparray.shape)
print("Data Type =", nparray.dtype)
print("Total Size in Bytes =", nparray.nbytes)

Dimension = 1
Size = 5
Shape = (5,)
Data Type = int64
Total Size in Bytes = 40


## Reshaping

In [22]:
numpy.array([[1, 2, 3, 4], [10, 11, 12, 13]]).reshape((4, 2))

array([[ 1,  2],
       [ 3,  4],
       [10, 11],
       [12, 13]])

## Aranging

> `arange()` gives a 1D numpy array, works similarly to Python's `range()`

- You can use the Math like notation of matrices for subscripting
- Consider a matrix `M(4,4)`
- Then indexing like `M[0,0]` will give the element at `Row 1, Column 1`

In [3]:
import numpy

a_matrix = numpy.arange(12).reshape((3, 4))
print(a_matrix)

print(numpy.ix_())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 8  9 10 11]]


## Axis

In [21]:
import numpy

a = numpy.arange(32).reshape(8, 4)
print(a)
print("Matrix Maximum =", a.max())
print("Matrix Minimum =", a.min())
print("Matrix Sum =", a.sum())
print("Row Maximum =", a.max(axis=0))
print("Column Maximum =", a.max(axis=1))
print("Row Minimum =", a.min(axis=0))
print("Column Minimum =", a.min(axis=1))
print("Row Sum =", a.sum(axis=0))
print("Column Sum =", a.sum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
Matrix Maximum = 31
Matrix Minimum = 0
Matrix Sum = 496
Row Maximum = [28 29 30 31]
Column Maximum = [ 3  7 11 15 19 23 27 31]
Row Minimum = [0 1 2 3]
Column Minimum = [ 0  4  8 12 16 20 24 28]
Row Sum = [112 120 128 136]
Column Sum = [  6  22  38  54  70  86 102 118]


## Operator Overloading for numpy array

In [28]:
A = numpy.array([[1, 2, 3], [3, 2, 1]])
B = numpy.array([[0, 0, 0], [1, 1, 1]])

print(A)
print(B)
print("A + B = \n", A + B)
print("A + B = \n", A - B)
print("A + B = \n", A * B)
# scaler *

[[1 2 3]
 [3 2 1]]
[[0 0 0]
 [1 1 1]]
A + B = 
 [[1 2 3]
 [4 3 2]]


## Concatenation

In [27]:
# first column of A and B combined will be the first column of VSTACK and likewise
print(numpy.vstack((A, B)))
# first row and A and B combined will be the first row of HSTACK and likewise
print(numpy.hstack((A, B)))

[[1 2 3]
 [3 2 1]
 [0 0 0]
 [1 1 1]]
[[1 2 3 0 0 0]
 [3 2 1 1 1 1]]


# August 30 2023

## `numpy` Array Slicing

> `[R]` is by default **Row Major Order**

> `[R_start : R_stop : R_step, C_start : C_stop : C_step]`

> `start` is  **inclusive**

> `stop` is **exclusive**

In [8]:
import numpy

array = numpy.arange(9).reshape(3, 3)
print(array)

# slices the R0:R1, C1:C2
print(array[:2, 1:])

# slices the R2:C1:C2:C3
print(array[2])

# slices the R0:R1:R2, C0:C1
print(array[:, :2])

# slices the R1, C0:C1
print(array[1:2, :2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2]
 [4 5]]
[6 7 8]
[[0 1]
 [3 4]
 [6 7]]
[[3 4]]


# `numpy` Array Indexing using Boolean Values

In [3]:
import numpy

names = numpy.array(["Emma", "Wednesday", "Bryan", "Tiffany"])

print(names == "Emma")
print(names == "Witch")
print(names == "Dylan")
print(names == "Tiffany")

[ True False False False]
[False False False False]
[False False False False]
[False False False  True]


In [20]:
import numpy

array = numpy.array(
    [
        numpy.arange(0, 6),
        numpy.arange(10, 16),
        numpy.arange(20, 26),
        numpy.arange(30, 36),
        numpy.arange(40, 46),
        numpy.arange(50, 56),
    ]
)
print(array)

# prime diagonal, you can shift it
print(array[(0, 1, 2, 3, 4, 5), (0, 1, 2, 3, 4, 5)])

# vector selection
print(array[3:, (0, 2, 5)])

# singleton selection using a Boolean mask
mask = numpy.array([1, 0, 1, 0, 0, 1], dtype=numpy.bool_)
print(array[mask, 2])

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[ 0 11 22 33 44 55]
[[30 32 35]
 [40 42 45]
 [50 52 55]]
[ 2 22 52]


## Fancier slicing

In [23]:
# same as above

# Index using Tuple
print(array[(range(6)),])

# Index using List

# Index using Boolean Array

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


## Sorting `numpy` Array

> Using `sort()`

> The `arg` `axis` sorts the `numpy.array()` in that COLUMN

In [49]:
array = numpy.array(
    [
        numpy.random.randint(-3, 7, 3),
        numpy.random.randint(-3, 7, 3),
        numpy.random.randint(-3, 7, 3),
    ]
)
print(array)
print(numpy.sort(-array))
# Sorts along the C0
print(numpy.sort(array, axis=0))
# Sorts along the C1
print(numpy.sort(array, axis=1))
# Sorts along the nth Row
print(numpy.sort(array, axis=-1))

[[ 5 -1  2]
 [ 4 -3  0]
 [-2  4  5]]
[[-5 -2  1]
 [-4  0  3]
 [-5 -4  2]]
[[-2 -3  0]
 [ 4 -1  2]
 [ 5  4  5]]
[[-1  2  5]
 [-3  0  4]
 [-2  4  5]]
[[-1  2  5]
 [-3  0  4]
 [-2  4  5]]


## The `argsort()`, WHAT?

> `argsort()` returns the `indices` that would sort an array [Read more...](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)

In [44]:
print(numpy.argsort(array))

[[3 1 5 2 0 4 6]
 [3 4 5 6 0 2 1]]


## `numpy` **Structured Array**

In [11]:
import numpy

structure = numpy.dtype(
    [
        ("name", numpy.unicode_, 64),
        ("age", numpy.ushort),
        ("alive", numpy.bool_),
    ]
)

ramayana = numpy.array(
    [
        ("Ram", 24, False),
        ("Sita", 21, False),
        ("Lakshman", 23, False),
        ("Ravan", 54, False),
    ],
    dtype=structure,
)

print(ramayana)

[('Ram', 24, False) ('Sita', 24, False) ('Lakshman', 24, False)
 ('Ravan', 24, False)]


# 31 August 2023

## `Numpy`
- `np.where()`   
    1. `returns` indices that satisfy the `condition`
    2. This acts as a **mask**
    3. Apply the **mask** as `numpy.array(mask)`
---
- Aggregation Functions:    
    1. `np.mean()`
    2. `np.max()`

In [22]:
import numpy as np

ramayana["age"]

print(ramayana[np.where(ramayana["age"] > 20)])

[('Ram', 24, False) ('Sita', 24, False) ('Lakshman', 24, False)
 ('Ravan', 24, False)]


# 4 September 2023

## `Pandas`

- ```Series```, for `1D` data
- ```DataFrame```, for `2D` data

> You can use manual indices

## `pandas.Series`

In [6]:
from prettier import printf
import pandas as pd
import numpy as np

data = pd.Series(np.array(np.arange(0.25, 1, 0.25)))
printf(data)
printf(data.values)
printf(data.index)
printf(data[0])


data = pd.Series(np.array(np.arange(0.25, 1.25, 0.25)), index=[10, 20, 30, 40])
printf(data[10])

data = pd.Series(
    np.array(np.arange(0.25, 1.25, 0.25)), index=["25%", "50%", "75%", 100]
)
printf(data["50%"])
printf(data[100])

------------------------------------------------------------------------------
(0    0.25
1    0.50
2    0.75
dtype: float64,)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
(array([0.25, 0.5 , 0.75]),)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
(RangeIndex(start=0, stop=3, step=1),)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
(0.25,)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
(0.25,)
------------------------------------------------------------------------------
------------------------------------------------------------------------------

## `pandas.DataFrame`

### Using `List`

In [5]:
from prettier import printf
import pandas as pd
import numpy as np

usa_ca_population = [32497091, 32411]
usa_tx_population = [213141, 2444]
usa_ny_population = [138971897, 7891]

df_population = pd.DataFrame(
    [usa_ca_population, usa_tx_population, usa_ny_population],
    index=["California", "Texas", "New York"],
    columns=["Population", "Area"],
)
printf(df_population)

df_colors = pd.DataFrame(
    [["yellow", 50], ["red", 25], ["orange", 90]],
    index=["Mango", "Apple", "Tangerine"],
    columns=["Color", "Count"],
)
print(df_colors)

------------------------------------------------------------------------------
(            Population   Area
California    32497091  32411
Texas           213141   2444
New York     138971897   7891,)
------------------------------------------------------------------------------
            Color  Count
Mango      yellow     50
Apple         red     25
Tangerine  orange     90


### Using `Dict`

In [2]:
from prettier import printf
import pandas as pd

fruit_color = {
    "mango": "yellow",
    "apple": "red",
    "peach": "pink",
    "tangerine": "orange",
}
fruit_count = {
    "mango": "50",
    "apple": "25",
    "peach": "75",
    "tangerine": "100",
}

fruit = {"color": fruit_color, "count": fruit_count}
df = pd.DataFrame(fruit)
printf(df)
printf(df.index)
printf(df.columns)

------------------------------------------------------------------------------
(            color count
mango      yellow    50
apple         red    25
peach        pink    75
tangerine  orange   100,)
------------------------------------------------------------------------------
(Index(['mango', 'apple', 'peach', 'tangerine'], dtype='object'),)
------------------------------------------------------------------------------
(Index(['color', 'count'], dtype='object'),)


### `pandas.DataFrame.loc()`

> access row using index

In [3]:
import pandas as pd
from prettier import printf

city_stats = pd.DataFrame(
    [
        ["Xavier", "Mexico", 41, 88.0],
        ["Xavier", "Toronto", 28, 79.0],
        ["Xavier", "Prague", 33, 81.0],
        ["Xavier", "Shanghai", 34, 80.0],
        ["Xavier", "Manchester", 38, 68.0],
        ["Xavier", "Cairo", 31, 61.0],
        ["Xavier", "Osaka", 37, 84.0],
    ],
    index=[x for x in range(101, 108, 1)],
    columns=["Name", "City", "Age", "Python Score"],
)

printf(city_stats)

printf(city_stats["City"])
printf(city_stats.loc[103])

------------------------------------------------------------------------------
(       Name        City  Age  Python Score
101  Xavier      Mexico   41          88.0
102  Xavier     Toronto   28          79.0
103  Xavier      Prague   33          81.0
104  Xavier    Shanghai   34          80.0
105  Xavier  Manchester   38          68.0
106  Xavier       Cairo   31          61.0
107  Xavier       Osaka   37          84.0,)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
(101        Mexico
102       Toronto
103        Prague
104      Shanghai
105    Manchester
106         Cairo
107         Osaka
Name: City, dtype: object,)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
(Name            Xavier
City            Prague
Age                 33
Python Score      81.0
Name: 103,

### using `.` to access column

In [4]:
printf(city_stats.Age)

------------------------------------------------------------------------------
(101    41
102    28
103    33
104    34
105    38
106    31
107    37
Name: Age, dtype: int64,)
------------------------------------------------------------------------------


### Hierarchical Indexing

In [15]:
import pandas as pd

weird_fruit_index = [
    ("Mango", "Yellow"),
    ("Mango", "Green"),
    ("Apple", "Red"),
    ("Apple", "Green"),
]

fruits = pd.DataFrame(
    [["Mango", "25"], ["Mango", "50"], ["Mango", "125"], ["Mango", "225"]],
    index=[weird_fruit_index],
    columns=["Fruit", "Count"],
)

print(fruits)
print(fruits.index)
# print(
# [i for i in fruits.index if i[1] == 'Green']
# )

for i in fruits.index:
    print(i[0])
# index=pd.MultiIndex.from_tuples(weird_fruit_index)
# print(index)

                 Fruit Count
(Mango, Yellow)  Mango    25
(Mango, Green)   Mango    50
(Apple, Red)     Mango   125
(Apple, Green)   Mango   225
MultiIndex([(('Mango', 'Yellow'),),
            ( ('Mango', 'Green'),),
            (   ('Apple', 'Red'),),
            ( ('Apple', 'Green'),)],
           )
('Mango', 'Yellow')
('Mango', 'Green')
('Apple', 'Red')
('Apple', 'Green')


# 5 September 2023

## Handling missing data

> Depends on the dataset

- Remove the entire tuple with the missing data points
- Average
- ...

> `Numpy's` ```nan``` type deals with this anomaly
- However, any operation with a ```nan``` type evaluates to ```nan``` itself.
- How do we deal with this then? 🤔

> We can, with the following in `pandas`:
- ```pandas.Series().fillna(method=?)```
- ```ffill```: propagates the previous value to the next `nan`
- ```bfill```: propagates the upcoming value to the previous `nan`

In [6]:
from prettier import printf
import pandas as pd

tuple_with_none = pd.Series([1, 2, 3, None, 0, 77.8, None])

printf(tuple_with_none.isnull())
printf(tuple_with_none.notnull())
print(tuple_with_none.fillna(method="ffill"))
print(tuple_with_none.fillna(method="bfill"))

------------------------------------------------------------------------------
(0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool,)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
(0     True
1     True
2     True
3    False
4     True
5     True
6    False
dtype: bool,)
------------------------------------------------------------------------------
0     1.0
1     2.0
2     3.0
3     3.0
4     0.0
5    77.8
6    77.8
dtype: float64
0     1.0
1     2.0
2     3.0
3     0.0
4     0.0
5    77.8
6     NaN
dtype: float64


## Working with a real [dataset](./dataset/president_heights.xlsx)

### ```read_excel()``` and ```head()```

In [3]:
from prettier import printf
import pandas as pd

ds = pd.read_excel("./dataset/president_heights.xlsx")
printf(ds.head(5))

------------------------------------------------------------------------------
(   order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183,)
------------------------------------------------------------------------------


# 11 September 2023

In [7]:
import pandas as pd

ds = pd.read_excel("./dataset/Q8_MortalityDataset.xlsx")

# take a peek at the dataset
printf(ds.head(5))

printf(ds.count())

------------------------------------------------------------------------------
(   AGE  HEIGHT  WEIGHT  CHOL   SMOKE BLOOD   MORT
0   20     176      77   195  nonsmo     b  alive
1   53     167      56   250  sigare     o   dead
2   44     170      80   304  sigare     a   dead
3   37     173      89   178  nonsmo     o  alive
4   26     170      71   206  sigare     o  alive,)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
(AGE       200
HEIGHT    200
WEIGHT    200
CHOL      200
SMOKE     200
BLOOD     200
MORT      200
dtype: int64,)
------------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   AGE     200 non-null    int64 
 1   HEIGHT  200 non-null    int64 
 2   WEIGHT  200 no

## ```.info()```

> Get some information on the dataset

In [12]:
print(ds.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   AGE     200 non-null    int64 
 1   HEIGHT  200 non-null    int64 
 2   WEIGHT  200 non-null    int64 
 3   CHOL    200 non-null    int64 
 4   SMOKE   200 non-null    object
 5   BLOOD   200 non-null    object
 6   MORT    200 non-null    object
dtypes: int64(4), object(3)
memory usage: 11.1+ KB
None


## ```.filter()```

> filter by ROW(s) or COLUMN(s)

In [11]:
ds.filter(items=["BLOOD", "HEIGHT"])

BLOOD  HEIGHT
0       b     176
1       o     167
2       a     170
3       o     173
4       o     170
..    ...     ...
195     a     174
196     b     172
197     a     170
198     o     165
199     b     178

[200 rows x 2 columns]

## ```.describe()```

> **Statistical summary** for only **numeric-valued** Column

In [13]:
ds.describe()

AGE     HEIGHT      WEIGHT        CHOL
count  200.000000  200.00000  200.000000  200.000000
mean    35.715000  172.35000   75.885000  233.600000
std      9.604426    6.77399   10.442076   44.766732
min     18.000000  156.00000   53.000000  107.000000
25%     28.750000  168.00000   68.750000  204.000000
50%     37.000000  172.00000   75.000000  232.000000
75%     42.000000  176.00000   82.000000  259.000000
max     58.000000  191.00000  110.000000  455.000000

## 
```python
@property
.shape
```

> `=> (R, C)`

In [14]:
ds.shape

(200, 7)

## ```.sample()```

> Randomly pick `n` records from the dataset for sampling

In [15]:
ds_sample = ds.sample(n=10)
print(ds_sample)

     AGE  HEIGHT  WEIGHT  CHOL   SMOKE BLOOD   MORT
155   38     169      73   198  sigare     a  alive
114   48     164      67   325  sigare     a  alive
17    30     181      74   191  nonsmo     a  alive
47    42     170      78   218  sigare     o  alive
48    28     169      96   189    pipe     b  alive
64    40     172      93   287  sigare     b   dead
73    34     170      69   207  sigare     b  alive
65    50     167      65   240  sigare     b  alive
109   36     170      81   190  nonsmo     o   dead
33    34     179      79   214  sigare     a  alive


## 
```python
@propery
.iloc
```

> Integer-based location

> Can take `range` like notation

In [25]:
printf(ds.iloc[33])
printf(ds.iloc[[33]])  # notice the inner `[]`
printf(ds.iloc[0:2, 1:3])
printf(ds.iloc[[0, 1]])

------------------------------------------------------------------------------
(AGE           34
HEIGHT       179
WEIGHT        79
CHOL         214
SMOKE     sigare
BLOOD          a
MORT       alive
Name: 33, dtype: object,)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
(    AGE  HEIGHT  WEIGHT  CHOL   SMOKE BLOOD   MORT
33   34     179      79   214  sigare     a  alive,)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
(   HEIGHT  WEIGHT
0     176      77
1     167      56,)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
(   AGE  HEIGHT  WEIGHT  CHOL   SMOKE BLOOD   MORT
0   20     176      77   195  nonsmo     b  alive
1   53     167      56   250  sigare  

## ```.groupby()```

> Groups the record according to the given column names

In [32]:
printf(ds_sample.groupby(by=["SMOKE", "BLOOD", "MORT"]).mean())
printf(ds_sample.groupby(by=["SMOKE", "BLOOD", "MORT"]).size())

------------------------------------------------------------------------------
(                     AGE      HEIGHT  WEIGHT        CHOL
SMOKE  BLOOD MORT                                       
nonsmo a     alive  30.0  181.000000    74.0  191.000000
       o     dead   36.0  170.000000    81.0  190.000000
pipe   b     alive  28.0  169.000000    96.0  189.000000
sigare a     alive  40.0  170.666667    73.0  245.666667
       b     alive  42.0  168.500000    67.0  223.500000
             dead   40.0  172.000000    93.0  287.000000
       o     alive  42.0  170.000000    78.0  218.000000,)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
(SMOKE   BLOOD  MORT 
nonsmo  a      alive    1
        o      dead     1
pipe    b      alive    1
sigare  a      alive    3
        b      alive    2
               dead     1
        o      alive    1
dtype: int64,)
----------------------------